#include "../Pad2.h"
void Plot_sigBG_PPMB() {
  gROOT->Macro("eeStyle.C");
  gStyle->SetOptTitle(0);
  gStyle->SetPadTickX(1);
  gStyle->SetPadTickY(1);
  gStyle->SetOptDate(0);
  gStyle->SetFrameLineWidth(3);
  gStyle->SetEndErrorSize(0);
  gStyle->SetErrorX(0);

  TFile *fAuAu = new TFile("/Users/luthien/worksdir/Run12PP200/ana/output/sig_2D_v0.root");
  TH1D *hSG = (TH1D *) ((TH2D *)fAuAu->Get("Signal"))->ProjectionX("hSG");
  TH1D *hBG = (TH1D *) ((TH2D *)fAuAu->Get("BackGround"))->ProjectionX("hBG");
  TH1D *hRY = (TH1D *) ((TH2D *)fAuAu->Get("RawYield"))->ProjectionX("hRY");
  TH1D *hRatio = (TH1D *)hRY->Clone("hRatio");
  hRatio->Divide(hBG);

  double x1 = -0.1;
  double x2 = 3.2;
  double y1 = 2e-9;
  double y2 = hSG->GetMaximum()*5;

  TCanvas *c1 = new TCanvas("c1","",800,900);
  c1->cd();
  pad1(c1);
  TH1D *d0 = new TH1D("d0","",1,x1,x2);
	d0->SetMinimum(y1);
	d0->SetMaximum(y2);
	d0->GetXaxis()->SetNdivisions(408);
	d0->GetXaxis()->SetTitle("Mass(e^{+}e^{-}) (GeV/c^{2})");
	d0->GetXaxis()->SetTitleOffset(0.9);
	d0->GetXaxis()->SetTitleSize(0.06);
	d0->GetXaxis()->SetLabelOffset(0.01);
	d0->GetXaxis()->SetLabelSize(0.045);
	d0->GetXaxis()->SetLabelFont(42);
	d0->GetXaxis()->SetTitleFont(42);
	d0->GetYaxis()->SetNdivisions(204);
	d0->GetYaxis()->SetTitle("dN/dM/dy (c^{2}/GeV)");
	d0->GetYaxis()->SetTitleOffset(1.0);
	d0->GetYaxis()->SetTitleSize(0.06);
	d0->GetYaxis()->SetLabelOffset(0.005);
	d0->GetYaxis()->SetLabelSize(0.045);
	d0->GetYaxis()->SetLabelFont(42);
	d0->GetYaxis()->SetTitleFont(42);
	d0->SetLineWidth(2);
	d0->Draw();
  hSG->SetMarkerStyle(24);
  hSG->SetMarkerColor(1);
  hSG->SetMarkerSize(1.2);
  hSG->Draw("epsame");
  hSG->SetMarkerSize(1.1);
  hSG->SetLineColor(1);
  hSG->SetLineWidth(2);
  //hSG->Draw("histsame");
  hBG->SetLineColor(2);
  hBG->SetLineWidth(2);
  hBG->Draw("histsame");
  hRY->SetMarkerStyle(20);
  hRY->SetMarkerColor(1);
  hRY->SetMarkerSize(1.2);
  hRY->Draw("psame");
  TLegend *t1_1 = new TLegend(0.6,0.7,0.9,0.9);
  t1_1->SetBorderSize(0);
  t1_1->SetFillColor(10);
  t1_1->SetTextSize(0.045);
  t1_1->SetTextFont(42);
  t1_1->AddEntry(hSG,"foreground","pl");
  t1_1->AddEntry(hBG,"background","l");
  t1_1->AddEntry(hRY,"raw yield","epl");
  t1_1->Draw("same");
  TLatex *t = new TLatex();
  t->SetTextFont(62);
  t->SetTextSize(0.055);
  t->DrawLatex(x1+0.05*(x2-x1),3e-8,"#sqrt{S_{NN}} = 200GeV p+p MinBias");

  pad2(c1);
  p2->SetLogy();
	y1 = 5e-2;
	y2 = 2000;//8.;
	TH2F *d1 = new TH2F("d1","",1,x1,x2,1,y1,y2);
	d1->GetXaxis()->SetNdivisions(208);
	d1->GetXaxis()->CenterTitle();
	d1->GetXaxis()->SetTitle("M_{ee} (GeV/c^{2})");
	d1->GetXaxis()->SetTitleOffset(0.95);
	d1->GetXaxis()->SetTitleSize(0.14);
	d1->GetXaxis()->SetLabelOffset(0.02);
	d1->GetXaxis()->SetLabelSize(0.1);
	d1->GetXaxis()->SetLabelFont(42);
	d1->GetXaxis()->SetTitleFont(42);
	d1->GetXaxis()->SetTickLength(0.055);
	d1->GetYaxis()->SetNdivisions(202);
	d1->GetYaxis()->SetTitle("S/B");
	d1->GetYaxis()->CenterTitle();
	d1->GetYaxis()->SetTitleOffset(0.45);
	d1->GetYaxis()->SetTitleSize(0.11);
	d1->GetYaxis()->SetLabelOffset(0.01);
	d1->GetYaxis()->SetLabelSize(0.1);
	d1->GetYaxis()->SetLabelFont(42);
	d1->GetYaxis()->SetTitleFont(42);
	d1->GetYaxis()->SetTickLength(0.043);
	d1->SetLineWidth(2);
	d1->Draw();
  hRatio->SetMarkerStyle(20);
  hRatio->SetMarkerColor(4);
  hRatio->SetMarkerSize(1.2);
  hRatio->SetLineColor(4);
  hRatio->SetLineWidth(2);
  hRatio->Draw("epsame");

  c1->SaveAs("SBRatio_PP_MinBias.eps");
  c1->SaveAs("SBRatio_PP_MinBias.gif");
}
